smartscigs/smartscigs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('write_article/', include('write_article.urls')),
    path('admin/', admin.site.urls),
]

smartscigs/write_article/urls.py
from django.urls import path

from . import views

app_name = 'write_article'
# 共有几个页面
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

smartscigs/write_article/models.py
from django.db import models

import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

smartscigs/write_article/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404

from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):                  #显示一个对象列表
    template_name = 'write_article/index.html'              #<app name>/<model name>_list.html 的默认模板
    context_object_name = 'latest_question_list'    #自动生成的 context 变量

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):               #显示一个特定类型对象的详细信息页面
    model = Question
    template_name = 'write_article/detail.html'             #默认情况下, 使用 <app name>/<model name>_detail.html 的模板


class ResultsView(generic.DetailView):              #确保 results 视图和 detail 视图在渲染时具有不同的外观
    model = Question
    template_name = 'write_article/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'write_article/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1      # 使用 F() 避免竞争条件
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('write_article:results', args=(question.id,)))

smartscigs/write_article/templates/write_article/detail.html
<form action="{% url 'write_article:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

smartscigs/write_article/templates/write_article/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'write_article:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No write_article are available.</p>
{% endif %}

smartscigs/write_article/templates/write_article/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'write_article:detail' question.id %}">Vote again?</a>